# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

og_image: ''

twitter_username: jekyllrb
twitter_url: 'http://example.com'
twitter_image: ''

github_username:  jekyll

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
  - uglifier
  # - autoprefixer-rails
  # - sprockets-es6

include:
  - 'fonts'
  - 'images'
  - '_pages'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# asset-pipeline settings
# assets:
#   compress:
#     css: true
#     js: true
#     # css: false | true | default - development: false, production: true
#     # js: false | true | default - development: false, production: true
assets:
  # cache: true
  compress:
    js: uglifier
  js_compressor: babel
  css_compressor: sass
  autosize: true
  debug: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  prefix: '/assets'
  assets:
    - 'application.css'
    - 'application.js'
    - '*.png'
    - '*.jpg'
  autowrite: true
  # cache: false | directory | default: .asset-cache
  # cache_type: memory | filesystem | default: filesystem
  # cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  autoprefixer:
    flexbox: no-2009
    browsers:
      - "last 2 versions"
      - "IE > 9"

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/images
    - _assets/bower
